/* Dữ liệu sản phẩm dùng chung cho san-pham.html (lưới lọc theo danh mục) và
   san-pham-chi-tiet.html (trang chi tiết, đọc ?id=... để chọn đúng sản phẩm).
   Thêm/sửa sản phẩm chỉ cần sửa mảng này — không phải sửa HTML. */
window.PRODUCTS = [
  {
    id: "headphone-inspire-xh1",
    category: "Âm thanh",
    tag: "AKENXI Audio",
    name: "Tai nghe chụp tai Inspire XH1",
    usp: "Chống ồn chủ động Smart ANC, driver 40mm, pin nghe liên tục 100 giờ.",
    desc: "Chống ồn chủ động, pin 100 giờ.",
    price: 2590000,
    oldPrice: 4401000,
    discount: "-41%",
    rating: 4.9,
    ratingCount: "312",
    images: [
      "images/products/akenxi_headphone01/AKENXI_Headphone_Web_01.jpg",
      "images/products/akenxi_headphone01/AKENXI_Headphone_Web_02.jpg",
      "images/products/akenxi_headphone01/AKENXI_Headphone_Web_03.jpg",
      "images/products/akenxi_headphone01/AKENXI_Headphone_Web_04.jpg",
      "images/products/akenxi_headphone01/AKENXI_Headphone_Web_05.jpg",
    ],
    highlights: [
      { title: "Chống ồn chủ động", desc: "Smart ANC lọc tiếng ồn xung quanh, tập trung vào âm nhạc.", img: 1 },
      { title: "Pin 100 giờ", desc: "Nghe liên tục cả tuần chỉ với một lần sạc.", img: 3 },
      { title: "Đệm tai êm ái", desc: "Chất liệu memory foam, đeo êm cả ngày dài.", img: 4 },
    ],
    tech: [
      { icon: "anc", title: "Smart ANC", desc: "Cảm biến kép, thích ứng theo môi trường theo thời gian thực." },
      { icon: "battery", title: "Pin 100 giờ", desc: "Sạc nhanh 10 phút dùng thêm 4 giờ nghe nhạc." },
      { icon: "driver", title: "Driver 40mm", desc: "Tái tạo dải âm rộng, bass sâu, treble rõ." },
      { icon: "bluetooth", title: "Bluetooth 5.3", desc: "Ghép đôi tức thì, kết nối ổn định tầm xa hơn." },
    ],
  },
  {
    id: "earphone-bass-bs1",
    category: "Âm thanh",
    tag: "AKENXI Audio",
    name: "Tai nghe TWS Bass BS1",
    usp: "Thiết kế open-ear đeo cả ngày không đau tai, bass sâu đặc trưng, chống nước IPX5.",
    desc: "Thiết kế open-ear, đeo cả ngày không đau tai.",
    price: 550000,
    oldPrice: 1156000,
    discount: "-52%",
    rating: 4.8,
    ratingCount: "1.204",
    images: [
      "images/products/akenxi_earphone01/AKENXI_web_01.jpg",
      "images/products/akenxi_earphone01/AKENXI_web_02.jpg",
      "images/products/akenxi_earphone01/AKENXI_web_03.jpg",
      "images/products/akenxi_earphone01/AKENXI_web_04.jpg",
      "images/products/akenxi_earphone01/AKENXI_web_05.jpg",
      "images/products/akenxi_earphone01/AKENXI_web_06.jpg",
    ],
    highlights: [
      { title: "Open-ear thoải mái", desc: "Không bịt kín tai, đeo cả ngày vẫn nghe được xung quanh.", img: 1 },
      { title: "Bass sâu", desc: "Driver tối ưu cho dải trầm mà vẫn gọn nhẹ.", img: 2 },
      { title: "Chống nước IPX5", desc: "Yên tâm khi tập luyện, đi mưa nhẹ.", img: 4 },
    ],
    tech: [
      { icon: "driver", title: "Driver bass-boost", desc: "Tối ưu dải trầm cho thể thao và di chuyển." },
      { icon: "waterproof", title: "IPX5", desc: "Chống nước, chống mồ hôi khi vận động." },
      { icon: "bluetooth", title: "Bluetooth 5.3", desc: "Kết nối ổn định, độ trễ thấp khi xem video." },
      { icon: "battery", title: "Case sạc nhanh", desc: "Sạc nhanh 10 phút dùng thêm nhiều giờ." },
    ],
  },
  {
    id: "earphone-eli-sport-2",
    category: "Âm thanh",
    tag: "AKENXI Audio",
    name: "Tai nghe TWS Eli Sport 2",
    usp: "Nhẹ, ôm tai chắc chắn khi vận động mạnh, chống ồn chủ động cho môi trường ồn ào.",
    desc: "Nhẹ, ôm tai chắc khi vận động.",
    price: 990000,
    oldPrice: 1520000,
    discount: "-35%",
    rating: 4.7,
    ratingCount: "876",
    images: [
      "images/products/akenxi_earphone02/AKENXI_web_01_1800x1800.jpg",
      "images/products/akenxi_earphone02/AKENXI_web_02_1800x1800.jpg",
      "images/products/akenxi_earphone02/AKENXI_web_03_1800x1800.jpg",
      "images/products/akenxi_earphone02/AKENXI_web_04_1800x1800.jpg",
      "images/products/akenxi_earphone02/AKENXI_web_05_1800x1800.jpg",
    ],
    highlights: [
      { title: "Ôm tai chắc chắn", desc: "Thiết kế móc tai thể thao, không rơi khi chạy nhảy.", img: 1 },
      { title: "Nhẹ gần như không cảm nhận", desc: "Đeo liên tục nhiều giờ tập luyện không mỏi.", img: 2 },
      { title: "Chống ồn chủ động", desc: "Tập trung vào âm nhạc kể cả ở phòng gym ồn ào.", img: 3 },
    ],
    tech: [
      { icon: "anc", title: "ANC thể thao", desc: "Lọc tiếng ồn nền, giữ lại tiếng còi báo an toàn." },
      { icon: "waterproof", title: "IPX7", desc: "Chống nước cao, chịu được mồ hôi và mưa lớn." },
      { icon: "bluetooth", title: "Bluetooth 5.3", desc: "Ghép đôi nhanh, ổn định khi vận động." },
      { icon: "battery", title: "Pin 8h + case", desc: "Tổng thời lượng lên đến 32 giờ cùng case sạc." },
    ],
  },
  {
    id: "earphone-aero-clip",
    category: "Âm thanh",
    tag: "AKENXI Audio",
    name: "Tai nghe TWS Aero Clip",
    usp: "Cảm biến chạm mượt, kết nối tức thì, kiểu dáng clip-on hiện đại.",
    desc: "Cảm biến chạm mượt, kết nối tức thì.",
    price: 790000,
    oldPrice: 1290000,
    discount: "-39%",
    rating: 4.6,
    ratingCount: "198",
    images: [
      "images/products/akenxi_earphone03/AKENXI_Web_01_1086x1448.jpg",
      "images/products/akenxi_earphone03/AKENXI_Web_02_1086x1448.jpg",
      "images/products/akenxi_earphone03/AKENXI_Web_03_1086x1448.jpg",
      "images/products/akenxi_earphone03/AKENXI_Web_04_1086x1448.jpg",
      "images/products/akenxi_earphone03/AKENXI_Web_05_1086x1448.jpg",
      "images/products/akenxi_earphone03/AKENXI_Web_06_1086x1448.jpg",
    ],
    highlights: [
      { title: "Cảm ứng chạm mượt", desc: "Điều khiển nhạc/cuộc gọi bằng một chạm nhẹ.", img: 1 },
      { title: "Kết nối tức thì", desc: "Mở nắp case là tự động ghép đôi với thiết bị.", img: 2 },
      { title: "Kiểu dáng clip-on", desc: "Gọn, thời trang, dễ tháo lắp nhanh.", img: 4 },
    ],
    tech: [
      { icon: "touch", title: "Cảm ứng vân tay", desc: "Bề mặt cảm ứng phản hồi nhanh, chính xác." },
      { icon: "bluetooth", title: "Bluetooth 5.3", desc: "Kết nối tức thì, ổn định trong bán kính xa." },
      { icon: "battery", title: "Pin 6h + case", desc: "Sạc nhanh, dùng cả ngày dài." },
      { icon: "driver", title: "Driver 10mm", desc: "Âm thanh cân bằng, rõ lời thoại." },
    ],
  },
  {
    id: "earphone-nova-clip",
    category: "Âm thanh",
    tag: "AKENXI Audio",
    name: "Tai nghe TWS Nova Clip",
    usp: "Case sạc nhỏ gọn bỏ túi, sạc nhanh 10 phút dùng cả ngày.",
    desc: "Case sạc nhỏ gọn, sạc nhanh 10 phút.",
    price: 850000,
    oldPrice: 1350000,
    discount: "-37%",
    rating: 4.7,
    ratingCount: "256",
    images: [
      "images/products/akenxi_earphone04/AKENXI_feature_01_1440x1080.jpg",
      "images/products/akenxi_earphone04/AKENXI_feature_02_1440x1080.jpg",
      "images/products/akenxi_earphone04/AKENXI_feature_03_1440x1080.jpg",
      "images/products/akenxi_earphone04/AKENXI_feature_04_1440x1080.jpg",
      "images/products/akenxi_earphone04/AKENXI_feature_05_1440x1080.jpg",
      "images/products/akenxi_earphone04/AKENXI_feature_06_1440x1080.jpg",
    ],
    highlights: [
      { title: "Case bỏ túi gọn", desc: "Nhỏ hơn 30% so với case thông thường.", img: 1 },
      { title: "Sạc nhanh 10 phút", desc: "Đủ dùng thêm nhiều giờ nghe nhạc.", img: 2 },
      { title: "Bền bỉ hằng ngày", desc: "Vỏ nhôm nguyên khối, chống trầy tốt.", img: 3 },
    ],
    tech: [
      { icon: "battery", title: "Sạc siêu tốc", desc: "10 phút sạc — nhiều giờ sử dụng." },
      { icon: "bluetooth", title: "Bluetooth 5.3", desc: "Độ trễ thấp, ổn định khi gọi video." },
      { icon: "driver", title: "Driver cân bằng", desc: "Âm thanh tự nhiên, không gắt cao độ." },
      { icon: "waterproof", title: "IPX4", desc: "Chống ẩm, chống mồ hôi nhẹ hằng ngày." },
    ],
  },
  {
    id: "charger-palm-1c-20w",
    category: "Sạc nhanh",
    tag: "AKENXI Charging",
    name: "Củ sạc nhanh Palm 1C 20W",
    usp: "Sạc đầy iPhone 15 trong 30 phút, công nghệ PD 3.0 an toàn cho pin.",
    desc: "Sạc đầy iPhone 15 trong 30 phút.",
    price: 180000,
    oldPrice: 306000,
    discount: "-41%",
    rating: 4.8,
    ratingCount: "2.031",
    images: [
      "images/products/akenxi_charger03/AKENXI_product_01_1600x1600.jpg",
      "images/products/akenxi_charger03/AKENXI_product_02_1600x1600.jpg",
      "images/products/akenxi_charger03/AKENXI_product_03_1600x1600.jpg",
      "images/products/akenxi_charger03/AKENXI_product_04_1600x1600.jpg",
    ],
    highlights: [
      { title: "Sạc đầy trong 30 phút", desc: "PD 3.0 20W, nhanh gấp 3 lần sạc thường.", img: 1 },
      { title: "Bỏ túi gọn nhẹ", desc: "Kích thước nhỏ hơn hộp diêm.", img: 2 },
      { title: "An toàn cho pin", desc: "Tự ngắt khi đầy, chống nóng, chống sốc điện.", img: 3 },
    ],
    tech: [
      { icon: "bolt", title: "PD 3.0 20W", desc: "Chuẩn sạc nhanh phổ biến cho iPhone/Android." },
      { icon: "shield", title: "Bảo vệ đa lớp", desc: "Chống quá nhiệt, quá dòng, đoản mạch." },
      { icon: "plug", title: "1 cổng USB-C", desc: "Tương thích cáp C to C và C to Lightning." },
    ],
  },
  {
    id: "charger-palm-cu-20w",
    category: "Sạc nhanh",
    tag: "AKENXI Charging",
    name: "Củ sạc Palm C+U 20W",
    usp: "Nhỏ gọn mang theo mọi lúc, 2 cổng sạc cùng lúc cho 2 thiết bị.",
    desc: "Nhỏ gọn, mang theo mọi lúc.",
    price: 190000,
    oldPrice: 299000,
    discount: "-36%",
    rating: 4.7,
    ratingCount: "1.418",
    images: [
      "images/products/akenxi_charger04/AKENXI_charger_01_1200x1200.jpg",
      "images/products/akenxi_charger04/AKENXI_charger_02_1200x1200.jpg",
      "images/products/akenxi_charger04/AKENXI_charger_03_1200x1200.jpg",
      "images/products/akenxi_charger04/AKENXI_charger_04_1200x1200.jpg",
      "images/products/akenxi_charger04/AKENXI_charger_05_1200x1200.jpg",
    ],
    highlights: [
      { title: "2 cổng cùng lúc", desc: "USB-C + USB-A, sạc song song 2 thiết bị.", img: 1 },
      { title: "Nhỏ gọn di động", desc: "Vừa túi áo, mang theo mọi chuyến đi.", img: 2 },
      { title: "Tương thích rộng", desc: "Dùng tốt cho điện thoại, tai nghe, đồng hồ.", img: 3 },
    ],
    tech: [
      { icon: "bolt", title: "PD/QC 20W", desc: "Hỗ trợ cả chuẩn PD và Quick Charge." },
      { icon: "plug", title: "2 cổng C + A", desc: "Sạc song song không giảm tốc độ đáng kể." },
      { icon: "shield", title: "An toàn IC", desc: "IC quản lý nhiệt độ và dòng điện thông minh." },
    ],
  },
  {
    id: "charger-gan-100w",
    category: "Sạc nhanh",
    tag: "AKENXI Charging",
    name: "Củ sạc GaN 100W Desktop",
    usp: "3 cổng cùng lúc, màn LED báo công suất thực, sạc đầy laptop trong tích tắc.",
    desc: "3 cổng cùng lúc, sạc đầy laptop trong tích tắc.",
    price: 990000,
    oldPrice: 1650000,
    discount: "-40%",
    rating: 4.9,
    ratingCount: "312",
    images: [
      "images/products/akenxi_charger100W_01/AKENXI_100W_Web_01.jpg",
      "images/products/akenxi_charger100W_01/AKENXI_100W_Web_02.jpg",
      "images/products/akenxi_charger100W_01/AKENXI_100W_Web_03.jpg",
      "images/products/akenxi_charger100W_01/AKENXI_100W_Web_04.jpg",
      "images/products/akenxi_charger100W_01/AKENXI_100W_Web_05.jpg",
      "images/products/akenxi_charger100W_01/AKENXI_100W_Web_06.jpg",
    ],
    highlights: [
      { title: "100W GaN", desc: "Sạc đầy MacBook Pro trong hơn 1 giờ.", img: 1 },
      { title: "Màn LED thông minh", desc: "Hiển thị công suất sạc thực tế theo thời gian thực.", img: 2 },
      { title: "3 cổng cùng lúc", desc: "2x USB-C + 1x USB-A, chia sẻ công suất thông minh.", img: 3 },
    ],
    tech: [
      { icon: "bolt", title: "GaN 100W", desc: "Nhỏ gọn hơn 40% so với sạc silicon cùng công suất." },
      { icon: "battery", title: "Sạc đa thiết bị", desc: "Laptop, điện thoại, tai nghe cùng lúc không giảm tốc quá nhiều." },
      { icon: "shield", title: "8 lớp bảo vệ", desc: "Chống quá nhiệt, quá áp, đoản mạch, quá dòng." },
      { icon: "plug", title: "3 cổng PD/QC", desc: "Tự nhận diện thiết bị, tối ưu công suất từng cổng." },
    ],
  },
  {
    id: "power-magpro-10000",
    category: "Nguồn điện",
    tag: "AKENXI Power",
    name: "Pin sạc dự phòng MagPro 10.000mAh",
    usp: "Sạc không dây từ tính chuẩn MagSafe, đầu ra USB-C 20W, kèm dây đeo tiện lợi.",
    desc: "Sạc không dây từ tính, đầu ra USB-C.",
    price: 690000,
    oldPrice: 1150000,
    discount: "-40%",
    rating: 4.7,
    ratingCount: "531",
    images: [
      "images/products/akenxi_charger02/AKENXI_product_1.jpeg",
      "images/products/akenxi_charger02/AKENXI_product_2.jpeg",
      "images/products/akenxi_charger02/AKENXI_product_4.jpeg",
      "images/products/akenxi_charger02/AKENXI_product_5.jpeg",
      "images/products/akenxi_charger02/AKENXI_product_6.jpeg",
    ],
    highlights: [
      { title: "Sạc từ tính MagSafe", desc: "Gắn thẳng sau iPhone, không cần dây.", img: 1 },
      { title: "10.000mAh", desc: "Đủ sạc đầy iPhone khoảng 2 lần.", img: 2 },
      { title: "Dây đeo tiện lợi", desc: "Treo túi/balo, không lo rơi rớt.", img: 3 },
    ],
    tech: [
      { icon: "magnet", title: "Từ tính chuẩn MagSafe", desc: "Định vị nam châm chính xác, không lệch tâm." },
      { icon: "bolt", title: "USB-C 20W", desc: "Vừa sạc không dây vừa sạc dây cùng lúc." },
      { icon: "battery", title: "10.000mAh", desc: "Dung lượng lớn trong thân hình mỏng nhẹ." },
    ],
  },
  {
    id: "cable-dura-240w",
    category: "Cáp",
    tag: "AKENXI Cable",
    name: "Cáp sạc C to C Dura 240W",
    usp: "Dây dù bện chịu lực, chịu gập 30.000 lần, hỗ trợ sạc nhanh 240W.",
    desc: "Dây dù bện, chịu gập 30.000 lần.",
    price: 120000,
    oldPrice: 156000,
    discount: "-23%",
    rating: 4.9,
    ratingCount: "3.402",
    images: [
      "images/products/akenxi_cable01/AKENXI_cable_01_1600x1600.jpg",
      "images/products/akenxi_cable01/AKENXI_cable_02_1600x1600.jpg",
      "images/products/akenxi_cable01/AKENXI_cable_03_1600x1600.jpg",
      "images/products/akenxi_cable01/AKENXI_cable_04_1600x1600.jpg",
      "images/products/akenxi_cable01/AKENXI_cable_05_1600x1600.jpg",
    ],
    highlights: [
      { title: "Chịu gập 30.000 lần", desc: "Dây dù bện bền hơn dây nhựa thường 5 lần.", img: 1 },
      { title: "Hỗ trợ 240W", desc: "Sạc nhanh cả laptop công suất cao.", img: 2 },
      { title: "Đầu nối nhôm", desc: "Chắc chắn, chống oxy hoá theo thời gian.", img: 3 },
    ],
    tech: [
      { icon: "plug", title: "USB-C to USB-C", desc: "Chuẩn PD 240W, tương thích laptop, điện thoại." },
      { icon: "shield", title: "Dây dù bện", desc: "Chống rối, chống đứt gãy ở phần khuỷu." },
      { icon: "bolt", title: "Truyền dữ liệu", desc: "Hỗ trợ đồng bộ dữ liệu tốc độ cao." },
    ],
  },
  {
    id: "cable-digital-display",
    category: "Cáp",
    tag: "AKENXI Cable",
    name: "Cáp sạc Digital Display 100W",
    usp: "Màn LED hiển thị công suất sạc thực tế, dây dù bện bền bỉ, hỗ trợ 100W.",
    desc: "Màn LED hiển thị công suất sạc thực tế.",
    price: 250000,
    oldPrice: 390000,
    discount: "-36%",
    rating: 4.6,
    ratingCount: "389",
    images: [
      "images/products/akenxi_cable02/AKENXI_Cable_Web_01_1600x1600.jpg",
      "images/products/akenxi_cable02/AKENXI_Cable_Web_02_1600x1600.jpg",
      "images/products/akenxi_cable02/AKENXI_Cable_Web_03_1600x1600.jpg",
      "images/products/akenxi_cable02/AKENXI_Cable_Web_04_1600x1600.jpg",
      "images/products/akenxi_cable02/AKENXI_Cable_Web_05_1600x1600.jpg",
      "images/products/akenxi_cable02/AKENXI_Cable_Web_06_1600x1600.jpg",
    ],
    highlights: [
      { title: "Màn LED công suất", desc: "Biết chính xác đang sạc bao nhiêu watt.", img: 1 },
      { title: "Hỗ trợ 100W", desc: "Sạc nhanh điện thoại lẫn laptop mỏng nhẹ.", img: 2 },
      { title: "Dây dù bện bền bỉ", desc: "Chịu gập, chống rối tốt khi mang theo.", img: 3 },
    ],
    tech: [
      { icon: "bolt", title: "PD 100W", desc: "Đủ sạc nhanh hầu hết laptop mỏng nhẹ hiện nay." },
      { icon: "touch", title: "Màn LED thời gian thực", desc: "Hiển thị watt đang truyền, dễ theo dõi." },
      { icon: "plug", title: "USB-C to USB-C", desc: "Đầu nối nhôm nguyên khối, tiếp xúc ổn định." },
    ],
  },
  {
    id: "cable-fast-100w-white",
    category: "Cáp",
    tag: "AKENXI Cable",
    name: "Cáp sạc C to C Fast 100W",
    usp: "Đầu nối nhôm nguyên khối bền bỉ, hỗ trợ sạc nhanh 100W, màu trắng thanh lịch.",
    desc: "Đầu nối nhôm nguyên khối, bền bỉ.",
    price: 150000,
    oldPrice: 220000,
    discount: "-32%",
    rating: 4.7,
    ratingCount: "724",
    images: [
      "images/products/akenxi_cable03/AKENXI_Cable_Web_01_1600x1600.jpg",
      "images/products/akenxi_cable03/AKENXI_Cable_Web_02_1600x1600.jpg",
      "images/products/akenxi_cable03/AKENXI_Cable_Web_03_1600x1600.jpg",
      "images/products/akenxi_cable03/AKENXI_Cable_Web_04_1600x1600.jpg",
      "images/products/akenxi_cable03/AKENXI_Cable_Web_05_1600x1600.jpg",
    ],
    highlights: [
      { title: "Đầu nối nhôm nguyên khối", desc: "Chắc chắn, chống oxy hoá, tiếp xúc ổn định.", img: 1 },
      { title: "Hỗ trợ 100W", desc: "Sạc nhanh điện thoại và laptop mỏng nhẹ.", img: 2 },
      { title: "Thiết kế trắng thanh lịch", desc: "Hợp mọi thiết bị, không ố vàng theo thời gian.", img: 3 },
    ],
    tech: [
      { icon: "plug", title: "USB-C to USB-C", desc: "Chuẩn PD 100W, tương thích đa thiết bị." },
      { icon: "shield", title: "Vỏ bọc TPE", desc: "Mềm, chống rối, bền theo thời gian sử dụng." },
      { icon: "bolt", title: "Truyền dữ liệu", desc: "Hỗ trợ đồng bộ dữ liệu tốc độ cao." },
    ],
  },
  {
    id: "mobile-magpro-mount",
    category: "Di động",
    tag: "AKENXI Mobile",
    name: "Giá đỡ điện thoại MagPro ô tô",
    usp: "Gắn từ tính chuẩn MagSafe, xoay 360°, kẹp chắc chắn trên mọi hành trình.",
    desc: "Gắn từ tính chuẩn MagSafe, xoay 360°.",
    price: 350000,
    oldPrice: 590000,
    discount: "-40%",
    rating: 4.8,
    ratingCount: "467",
    images: [
      "images/products/akenxi_mobile/1787118392516_6507308237392180214_6507308237392180214_71989e28df43e3b4e900d4a8b95a4ecc.jpg",
      "images/products/akenxi_mobile/1787118392590_6507308237392180214_6507308237392180214_ad05288ad2c516f2418c28b28e1ef5fb.jpg",
      "images/products/akenxi_mobile/1787118392671_6507308237392180214_6507308237392180214_85f839552484843f98739cc8b884231d.jpg",
      "images/products/akenxi_mobile/1787118392774_6507308237392180214_6507308237392180214_8dafe533959daa0dddc877e964530ba9.jpg",
      "images/products/akenxi_mobile/1787118392867_6507308237392180214_6507308237392180214_e02b56c292a6e5575ca61341be30d21c.jpg",
    ],
    highlights: [
      { title: "Từ tính MagSafe", desc: "Gắn/tháo điện thoại chỉ trong một chạm.", img: 1 },
      { title: "Xoay 360°", desc: "Dễ dàng chuyển ngang/dọc khi định vị hoặc gọi video.", img: 2 },
      { title: "Kẹp chắc chắn", desc: "Không rung lắc kể cả đường xóc.", img: 3 },
    ],
    tech: [
      { icon: "magnet", title: "Nam châm N52", desc: "Lực hút mạnh, giữ điện thoại ổn định." },
      { icon: "touch", title: "Xoay 360°", desc: "Khớp xoay linh hoạt, khoá góc chắc chắn." },
      { icon: "shield", title: "Chân đế bền bỉ", desc: "Hợp kim + silicone, không trầy táp-lô." },
    ],
  },
  {
    id: "speaker-karaoke-duo",
    category: "Phụ kiện",
    tag: "AKENXI Accessories",
    name: "Loa karaoke di động Duo Mic",
    usp: "Kèm 2 micro không dây, bass mạnh mẽ, pin karaoke liên tục nhiều giờ.",
    desc: "Kèm 2 micro không dây, bass mạnh mẽ.",
    price: 1290000,
    oldPrice: 1990000,
    discount: "-35%",
    rating: 4.6,
    ratingCount: "203",
    images: [
      "images/speaker_product/1786933684970_6507308237392180214_6507308237392180214_f4fe36da19a8099b43bdb5bdc5a078e9.jpg",
      "images/speaker_product/1786933684982_6507308237392180214_6507308237392180214_ac196428a57102447d757c469fa5ce1c.jpg",
      "images/speaker_product/1786933684996_6507308237392180214_6507308237392180214_4b964c2ab9fe634a4ffa8b742559e01d.jpg",
      "images/speaker_product/1786933685009_6507308237392180214_6507308237392180214_c64b4535dc039ade3b0bf188b8f54585.jpg",
      "images/speaker_product/1786933685022_6507308237392180214_6507308237392180214_c1de0bd5e4e90bc2091c9f8e44d7bc25.jpg",
    ],
    highlights: [
      { title: "Kèm 2 micro không dây", desc: "Song ca thoải mái, không lo dây vướng víu.", img: 1 },
      { title: "Bass mạnh mẽ", desc: "Loa bass lớn, âm thanh đầy trong không gian rộng.", img: 2 },
      { title: "Pin karaoke nhiều giờ", desc: "Hát xuyên suốt buổi tiệc không cần cắm điện.", img: 3 },
    ],
    tech: [
      { icon: "bluetooth", title: "Bluetooth 5.0", desc: "Kết nối điện thoại/TV phát nhạc dễ dàng." },
      { icon: "battery", title: "Pin karaoke", desc: "Sử dụng liên tục nhiều giờ mỗi lần sạc." },
      { icon: "driver", title: "Loa bass lớn", desc: "Âm thanh đầy, phù hợp không gian gia đình." },
    ],
  },
];
